improve menu
KejawenLab/SemartSkeleton pull request #63
Opened 2019-07-23 08:54 UTC by ad3n

improve menu

2019-07-23 09:42 UTC, samsonasik requested changes

2019-07-23 09:42 UTC, samsonasik commented on templates/generator/controller.php.twig
> -        } else {
yg bagian atas belum return early

2019-07-23 10:08 UTC, ad3n commented on templates/generator/controller.php.twig
> -        } else {
@samsonasik : solve

2019-07-23 12:59 UTC, samsonasik commented
mas @ad3n saya push untuk handle phpstan error notice

2019-07-23 13:24 UTC, samsonasik commented
travis green

2019-07-24 05:20 UTC, ad3n commented
@samsonasik makasih banyak

2019-07-24 05:27 UTC, merged